### ISSUE TITLE
Remove unsafe use of isVolatile

### ISSUE THREAD

**Issue by joeha480** [brailleapps/dotify.formatter.impl#20]
isVolatile can either be true or false for a block depending on the contents. The volatility cannot shift between different passes. That breaks the assumption about what it means when a block is volatile. The correct way to do it would be:
if (uai != null) { return true; }

This is ok, because uai is final and cannot change. I guess this may affect performance or even functionality.

**Comment by bertfrees** [comment]
It will affect performance but shouldn't affect functionality.

You can set volatile to true (if uai != null) and perform caching internally of course. Maybe this would be a nicer solution for isVolatile in general? Just remove the method and always perform caching internally?

**Comment by joeha480** [comment]
Closing this as it is not on master anymore
