### ISSUE TITLE
Support reference from a toc-entry or page-number to a span

### ISSUE THREAD

**Issue by bertfrees** [brailleapps/dotify.formatter.impl#25]
Currently it only works with blocks.

I have a patch ready that fixes this. If you want I'll make a pull request.

OBFL may have to be updated too.

**Comment by bertfrees** [comment]
Implemented in https://github.com/sbsdev/pipeline/commit/e46dfb9194afd9cc09747b57dbef050472c7f0d6

**Comment by bertfrees** [comment]
Joel would like to integrate this but first needs to look into how he should do it.

**Comment by bertfrees** [comment]
@joeha480 Could this be integrated now?

**Comment by bertfrees** [comment]
See also https://github.com/brailleapps/dotify.api/compare/master...sbsdev:refs-to-spans and https://github.com/brailleapps/dotify.formatter.impl/compare/master...sbsdev:refs-to-spans

**Comment by joeha480** [comment]
@bertfrees This can be closed now that #44 is merged, right?

**Comment by bertfrees** [comment]
Yes
