### ISSUE TITLE
Make variable available in pre-content about which fallbacks have been activated

### ISSUE THREAD

**Issue by bertfrees** [brailleapps/dotify.formatter.impl#60]
With fallback I mean renaming collections:

``` xml
<fallback>
   <rename collection="..." to="..."/>
</fallback>
```

NLB would like to have this feature because they want to make information available in the title pages about where notes can be found, at the bottom of pages or at the end of volumes. See https://github.com/snaekobbi/pipeline-mod-nlb/issues/32.

**Comment by kalaspuffar** [comment]
This should be moved to the OBFL issue tracker for more discussion.

**Comment by bertfrees** [comment]
I guess the current solution is satisfying enough. I'll close.
