### ISSUE TITLE
Improve volume breaking

### ISSUE THREAD

**Issue by bertfrees** [brailleapps/dotify.formatter.impl#72]
We need a more powerful volume breaking algorithm in Dotify, in order to comply with the [volume breaking rules specified in braille CSS](http://snaekobbi.github.io/braille-css-spec/#volume-breaking).

Related issues:
- [ ] https://github.com/snaekobbi/braille-css-spec/issues/2
- [ ] https://github.com/snaekobbi/functional-testing/issues/30

**Comment by bertfrees** [comment]
We can close this one right?

**Comment by joeha480** [comment]
I think so too.
