### ISSUE TITLE
Process TextAttributes in BrailleTranslator 

### ISSUE THREAD

**Issue by bertfrees** [brailleapps/dotify.formatter.impl#75]
Some preparations have been done, but MarkerProcessor is still used directly within ObflParser, and the versions of BrailleTranslator.translate() that accept TextAttributes are not used anywhere.

**Comment by joeha480** [comment]
Related to brailleapps/dotify.api#29

**Comment by joeha480** [comment]
Fixed in 37a8a265126ed3f345f7466350a250a4178458d2

Note that the TextAttribute is not used, but the new AttributeWithContext.
